const $=s=>document.querySelector(s); const app=$('#app');
const eur=n=>Number(n||0).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
const uid=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random());
const today=()=>new Date().toISOString().slice(0,10);
const storeKey='finanztracker_v2_accountId';
const cycles={monthly:['Monatlich',1],quarterly:['Vierteljährlich',1/3],yearly:['Jährlich',1/12]};
let tab='overview', analysisTab=0, modal=null, menu=false;
let state=load(); processDueRecurring(); save();
function defaults(){let a1=uid(),a2=uid();return{accounts:[{id:a1,name:'Giro',startBalance:1150,icon:'💳',color:'blue'},{id:a2,name:'Spar',startBalance:600,icon:'🏦',color:'purple'}],transactions:[{id:uid(),name:'Essen',amount:50,category:'Essen',accountId:a1,date:today(),note:'',isIncome:false}],recurring:[{id:uid(),name:'Gehalt',amount:1100,category:'Gehalt',accountId:a1,targetAccountId:'',billingCycle:'monthly',nextDueDate:today(),icon:'⬇️',note:'',isActive:true,type:'income'},{id:uid(),name:'Netflix',amount:12.99,category:'Streaming',accountId:a1,targetAccountId:'',billingCycle:'monthly',nextDueDate:today(),icon:'📺',note:'',isActive:true,type:'expense'}],goals:[{id:uid(),name:'Urlaub',targetAmount:1500,savedAmount:600,accountId:a2,icon:'✈️',color:'orange',targetDate:'',note:''}],budgets:[{id:uid(),category:'Essen',limit:200,icon:'🍴',color:'orange'}],categories:['Essen','Shopping','Auto','Freizeit','Gesundheit','Bildung','Haushalt','Kleidung','Sonstiges'],lastRecurringRun:{}}}
function load(){try{return JSON.parse(localStorage.getItem(storeKey))||defaults()}catch{return defaults()}}function save(){localStorage.setItem(storeKey,JSON.stringify(state))}
function acc(id){return state.accounts.find(a=>a.id===id)} function accName(id){return acc(id)?.name||'Konto gelöscht'}
function advanceDate(date,cycle){let d=new Date(date+'T00:00:00'); if(cycle==='monthly')d.setMonth(d.getMonth()+1); if(cycle==='quarterly')d.setMonth(d.getMonth()+3); if(cycle==='yearly')d.setFullYear(d.getFullYear()+1); return d.toISOString().slice(0,10)}
function processDueRecurring(){let changed=false; let now=today(); state.recurring.forEach(r=>{let guard=0; while(r.isActive&&r.nextDueDate&&r.nextDueDate<=now&&guard<24){let key=r.id+'_'+r.nextDueDate;if(!state.lastRecurringRun[key]){if(r.type==='transfer'){state.transactions.push({id:uid(),name:r.name,amount:+r.amount,category:'Umbuchung',accountId:r.accountId,targetAccountId:r.targetAccountId,date:r.nextDueDate,note:'Automatisch durch Vertrag',isIncome:false,isTransfer:true})}else{state.transactions.push({id:uid(),name:r.name,amount:+r.amount,category:r.category,accountId:r.accountId,date:r.nextDueDate,note:'Automatisch durch Vertrag',isIncome:r.type==='income'})}state.lastRecurringRun[key]=true;changed=true}r.nextDueDate=advanceDate(r.nextDueDate,r.billingCycle);changed=true;guard++}}); if(changed)save()}
function accountBalance(id){let a=acc(id); if(!a)return 0; let b=+a.startBalance||0; state.transactions.forEach(t=>{if(t.isTransfer){if(t.accountId===id)b-=+t.amount;if(t.targetAccountId===id)b+=+t.amount}else if(t.accountId===id)b+=t.isIncome?+t.amount:-(+t.amount)}); return b}
function totalBalance(){return state.accounts.reduce((s,a)=>s+accountBalance(a.id),0)}
function monthTx(){let m=today().slice(0,7);return state.transactions.filter(t=>(t.date||'').slice(0,7)===m)}
function monthlyIncome(){return monthTx().filter(t=>t.isIncome&&!t.isTransfer).reduce((s,t)=>s+ +t.amount,0)+state.recurring.filter(r=>r.isActive&&r.type==='income').reduce((s,r)=>s+(+r.amount)*cycles[r.billingCycle][1],0)}
function monthlyExpenses(){return monthTx().filter(t=>!t.isIncome&&!t.isTransfer).reduce((s,t)=>s+ +t.amount,0)+state.recurring.filter(r=>r.isActive&&r.type==='expense').reduce((s,r)=>s+(+r.amount)*cycles[r.billingCycle][1],0)}
function spentInCategory(c){return monthTx().filter(t=>!t.isIncome&&!t.isTransfer&&t.category===c).reduce((s,t)=>s+ +t.amount,0)+state.recurring.filter(r=>r.isActive&&r.type==='expense'&&r.category===c).reduce((s,r)=>s+(+r.amount)*cycles[r.billingCycle][1],0)}
function categoryTotals(){return [...new Set([...state.categories,...state.recurring.filter(r=>r.type==='expense').map(r=>r.category)])].map(c=>({category:c,total:spentInCategory(c)})).filter(x=>x.total>0).sort((a,b)=>b.total-a.total)}
function last6(){let out=[];for(let i=5;i>=0;i--){let d=new Date();d.setMonth(d.getMonth()-i);let ym=d.toISOString().slice(0,7), name=d.toLocaleString('de-DE',{month:'short'});let inc=state.transactions.filter(t=>(t.date||'').slice(0,7)===ym&&t.isIncome&&!t.isTransfer).reduce((s,t)=>s+ +t.amount,0)+state.recurring.filter(r=>r.isActive&&r.type==='income').reduce((s,r)=>s+(+r.amount)*cycles[r.billingCycle][1],0);let exp=state.transactions.filter(t=>(t.date||'').slice(0,7)===ym&&!t.isIncome&&!t.isTransfer).reduce((s,t)=>s+ +t.amount,0)+state.recurring.filter(r=>r.isActive&&r.type==='expense').reduce((s,r)=>s+(+r.amount)*cycles[r.billingCycle][1],0);out.push({month:name,income:inc,expenses:exp,balance:inc-exp})}return out}
function nav(){return `<div class="tabs">${[['overview','🏠','Übersicht'],['recurring','📄','Verträge'],['analysis','◔','Analyse'],['savings','▣','Sparen'],['budgets','☷','Budgets']].map(x=>`<button class="tab ${tab===x[0]?'active':''}" onclick="tab='${x[0]}';render()"><span>${x[1]}</span>${x[2]}</button>`).join('')}</div>`}
function shell(content,title='Übersicht',plus=true){app.innerHTML=`<div class="wrap"><div class="top"><div class="title">${title}</div>${plus?'<button class="plus" onclick="menu=!menu;renderMenu()">+</button>':''}</div>${content}</div>${nav()}<div id="fab" class="fabmenu ${menu?'show':''}"><button onclick="openModal('tx')">Buchung</button><button onclick="openModal('rec')">Vertrag</button><button onclick="openModal('acc')">Konto</button><button onclick="openModal('goal')">Sparziel</button><button onclick="openModal('budget')">Budget</button></div>`; renderMenu(); if(tab==='analysis')setTimeout(drawCharts,0)}
function renderMenu(){let f=$('#fab'); if(f)f.classList.toggle('show',menu)}
function render(){menu=false;processDueRecurring(); if(tab==='overview')return overview(); if(tab==='recurring')return recurring(); if(tab==='analysis')return analysis(); if(tab==='savings')return savings(); if(tab==='budgets')return budgets()}
function overview(){let inc=monthlyIncome(), exp=monthlyExpenses(), rem=inc-exp; shell(`<div class="hero"><h2>Gesamtvermögen</h2><div class="balance">${eur(totalBalance())}</div><div class="stats"><div class="stat"><span>Einnahmen</span><b>${eur(inc)}</b></div><div class="stat red"><span>Ausgaben</span><b>${eur(exp)}</b></div></div><div class="remain">● Noch ${eur(rem)} verfügbar</div></div><div class="card"><div class="head"><h3>Konten</h3><button class="link" onclick="openManage('acc')">Bearbeiten</button></div>${state.accounts.map(a=>row(a.icon,a.name,'Kontostand',eur(accountBalance(a.id)),'',`openModal('acc','${a.id}')`)).join('')}</div><div class="card"><div class="head"><h3>Letzte Buchungen</h3></div>${state.transactions.slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,10).map(t=>txRow(t)).join('')||'<div class="empty">Keine Buchungen</div>'}<button class="link" onclick="openManage('tx')">Alle Buchungen anzeigen</button></div>`,'Übersicht')}
function row(icon,title,sub,amount,cls='',click=''){return `<div class="row" ${click?`onclick="${click}"`:''}><div class="ico ${cls}">${icon}</div><div class="main"><b>${title}</b><div class="sub">${sub}</div></div><div class="amount">${amount}</div></div>`}
function txRow(t){let s=t.isTransfer?`${accName(t.accountId)} → ${accName(t.targetAccountId)}`:`${t.category} • ${accName(t.accountId)} • ${new Date(t.date+'T00:00:00').toLocaleDateString('de-DE')}`;let sign=t.isTransfer?'↔ ':t.isIncome?'+':'-';return row(t.isIncome?'⬇️':t.isTransfer?'↔️':'🍴',t.name,s,sign+eur(t.amount),t.isIncome?'green':t.isTransfer?'purple':'orange',`openModal('tx','${t.id}')`)}
function recurring(){let groups=[['income','Einnahmen'],['expense','Ausgaben'],['transfer','Umbuchungen']]; let fixed=state.recurring.filter(r=>r.isActive&&r.type==='expense').reduce((s,r)=>s+(+r.amount)*cycles[r.billingCycle][1],0); shell(`<div class="card"><div class="head"><div><div class="sub">Monatliche Fixkosten</div><h3>${eur(fixed)}</h3></div><div><div class="sub">Jährlich</div><h3>${eur(fixed*12)}</h3></div></div></div>${groups.map(g=>{let arr=state.recurring.filter(r=>r.type===g[0]&&r.isActive);return arr.length?`<div class="listTitle">${g[1]}</div><div class="card">${arr.map(r=>recRow(r)).join('')}</div>`:''}).join('')}${state.recurring.some(r=>!r.isActive)?`<div class="listTitle">Pausiert</div><div class="card">${state.recurring.filter(r=>!r.isActive).map(r=>recRow(r)).join('')}</div>`:''}`,'Verträge')}
function recRow(r){let sub=`${cycles[r.billingCycle][0]} • ${accName(r.accountId)} • fällig ${new Date(r.nextDueDate+'T00:00:00').toLocaleDateString('de-DE')}`;let val=(r.type==='income'?'+':r.type==='transfer'?'↔ ':'-')+eur(r.amount);return row(r.icon||'📄',r.name,sub,val,r.type==='income'?'green':r.type==='transfer'?'purple':'red',`openModal('rec','${r.id}')`)}
function analysis(){let cats=categoryTotals(); shell(`<div class="seg"><button class="${analysisTab===0?'active':''}" onclick="analysisTab=0;render()">Kategorien</button><button class="${analysisTab===1?'active':''}" onclick="analysisTab=1;render()">Verlauf</button><button class="${analysisTab===2?'active':''}" onclick="analysisTab=2;render()">Saldo</button></div>${analysisTab===0?`<div class="card"><div class="head"><h3>Ausgaben nach Kategorie</h3></div><canvas id="pie"></canvas>${cats.map(c=>`<div class="row"><div class="main"><b>${c.category}</b></div><div class="amount">${eur(c.total)}</div></div>`).join('')||'<div class="empty">Keine Daten</div>'}</div><div class="card"><div class="head"><h3>Fixkosten Verträge</h3></div>${state.recurring.filter(r=>r.isActive&&r.type==='expense').map(r=>row(r.icon,r.name,cycles[r.billingCycle][0],eur((+r.amount)*cycles[r.billingCycle][1]),'red',`openModal('rec','${r.id}')`)).join('')||'<div class="empty">Keine Fixkosten</div>'}</div>`:analysisTab===1?`<div class="card"><div class="head"><h3>Einnahmen vs. Ausgaben</h3></div><canvas id="bars"></canvas></div>`:`<div class="card"><div class="head"><h3>Saldo-Entwicklung</h3></div><canvas id="line"></canvas>${last6().map(m=>`<div class="row"><div class="main"><b>${m.month}</b></div><div class="sub">+${eur(m.income)} / -${eur(m.expenses)}</div><div class="amount ${m.balance<0?'danger':'pos'}">${eur(m.balance)}</div></div>`).join('')}</div>`}`,'Analyse',false)}
function savings(){let saved=state.goals.reduce((s,g)=>s+ +g.savedAmount,0), target=state.goals.reduce((s,g)=>s+ +g.targetAmount,0);shell(`<div class="card"><div class="head"><div><div class="sub">Gesamt gespart</div><h3>${eur(saved)}</h3></div><div><div class="sub">Gesamtziel</div><h3>${eur(target)}</h3></div></div><div class="progress"><div class="bar green" style="width:${target?Math.min(saved/target*100,100):0}%"></div></div></div><div class="card"><div class="head"><h3>Meine Ziele</h3></div>${state.goals.map(g=>{let p=g.targetAmount?Math.min(g.savedAmount/g.targetAmount,1):0;return `<div class="row" onclick="openModal('goal','${g.id}')"><div class="ico ${g.color}">${g.icon}</div><div class="main"><b>${g.name}</b><div class="sub">${accName(g.accountId)} • ${eur(g.savedAmount)} von ${eur(g.targetAmount)}</div><div class="progress"><div class="bar green" style="width:${p*100}%"></div></div></div><div class="amount">${Math.round(p*100)}%</div></div>`}).join('')||'<div class="empty">Keine Ziele</div>'}</div>`,'Sparen')}
function budgets(){let limit=state.budgets.reduce((s,b)=>s+ +b.limit,0), spent=state.budgets.reduce((s,b)=>s+spentInCategory(b.category),0);shell(`<div class="card"><div class="head"><div><div class="sub">Ausgegeben</div><h3>${eur(spent)}</h3></div><div><div class="sub">Budget gesamt</div><h3>${eur(limit)}</h3></div></div><div class="progress"><div class="bar ${spent>limit?'red':''}" style="width:${limit?Math.min(spent/limit*100,100):0}%"></div></div></div><div class="card"><div class="head"><h3>Kategorien</h3></div>${state.budgets.map(b=>{let sp=spentInCategory(b.category),p=b.limit?Math.min(sp/b.limit,1):0;return `<div class="row" onclick="openModal('budget','${b.id}')"><div class="ico ${b.color}">${b.icon}</div><div class="main"><b>${b.category}</b><div class="sub">${eur(sp)} / ${eur(b.limit)}</div><div class="progress"><div class="bar ${sp>b.limit?'red':''}" style="width:${p*100}%"></div></div></div><div class="amount ${sp>b.limit?'danger':''}">${sp>b.limit?'!':''}</div></div>`}).join('')||'<div class="empty">Keine Budgets</div>'}</div>`,'Budgets')}
function openManage(type){openModal(type)}
function optionAccounts(sel=''){return state.accounts.map(a=>`<option value="${a.id}" ${sel===a.id?'selected':''}>${a.name}</option>`).join('')}
function openModal(type,id=''){menu=false;let obj=(type==='tx'?state.transactions:type==='rec'?state.recurring:type==='acc'?state.accounts:type==='goal'?state.goals:state.budgets).find(x=>x.id===id)||{};let is=!!id;let title={tx:is?'Buchung bearbeiten':'Neue Buchung',rec:is?'Vertrag bearbeiten':'Neuer Vertrag',acc:is?'Konto bearbeiten':'Neues Konto',goal:is?'Sparziel bearbeiten':'Neues Sparziel',budget:is?'Budget bearbeiten':'Neues Budget'}[type];let html='';
if(type==='tx')html=`<div class="grid2"><div class="field"><label>Typ</label><select id="f_type"><option value="expense" ${!obj.isIncome&&!obj.isTransfer?'selected':''}>Ausgabe</option><option value="income" ${obj.isIncome?'selected':''}>Einnahme</option><option value="transfer" ${obj.isTransfer?'selected':''}>Umbuchung</option></select></div><div class="field"><label>Datum</label><input id="f_date" type="date" value="${obj.date||today()}"></div></div><div class="field"><label>Name</label><input id="f_name" value="${obj.name||''}"></div><div class="grid2"><div class="field"><label>Betrag</label><input id="f_amount" type="number" step="0.01" value="${obj.amount||''}"></div><div class="field"><label>Kategorie</label><input id="f_cat" value="${obj.category||'Essen'}"></div></div><div class="grid2"><div class="field"><label>Konto</label><select id="f_acc">${optionAccounts(obj.accountId||state.accounts[0]?.id)}</select></div><div class="field"><label>Zielkonto</label><select id="f_tacc">${optionAccounts(obj.targetAccountId||state.accounts[1]?.id||state.accounts[0]?.id)}</select></div></div><div class="field"><label>Notiz</label><textarea id="f_note">${obj.note||''}</textarea></div>`;
if(type==='rec')html=`<div class="grid2"><div class="field"><label>Art</label><select id="f_type"><option value="expense" ${obj.type==='expense'?'selected':''}>Ausgabe</option><option value="income" ${obj.type==='income'?'selected':''}>Einnahme</option><option value="transfer" ${obj.type==='transfer'?'selected':''}>Umbuchung</option></select></div><div class="field"><label>Rhythmus</label><select id="f_cycle"><option value="monthly" ${obj.billingCycle==='monthly'?'selected':''}>Monatlich</option><option value="quarterly" ${obj.billingCycle==='quarterly'?'selected':''}>Vierteljährlich</option><option value="yearly" ${obj.billingCycle==='yearly'?'selected':''}>Jährlich</option></select></div></div><div class="field"><label>Name</label><input id="f_name" value="${obj.name||''}"></div><div class="grid2"><div class="field"><label>Betrag</label><input id="f_amount" type="number" step="0.01" value="${obj.amount||''}"></div><div class="field"><label>Kategorie</label><input id="f_cat" value="${obj.category||'Streaming'}"></div></div><div class="grid2"><div class="field"><label>Konto</label><select id="f_acc">${optionAccounts(obj.accountId||state.accounts[0]?.id)}</select></div><div class="field"><label>Zielkonto</label><select id="f_tacc">${optionAccounts(obj.targetAccountId||state.accounts[1]?.id||state.accounts[0]?.id)}</select></div></div><div class="grid2"><div class="field"><label>Nächste Fälligkeit</label><input id="f_date" type="date" value="${obj.nextDueDate||today()}"></div><div class="field"><label>Aktiv</label><select id="f_active"><option value="true" ${obj.isActive!==false?'selected':''}>Aktiv</option><option value="false" ${obj.isActive===false?'selected':''}>Pausiert</option></select></div></div><div class="field"><label>Symbol</label><input id="f_icon" value="${obj.icon||'📄'}"></div><div class="field"><label>Notiz</label><textarea id="f_note">${obj.note||''}</textarea></div>`;
if(type==='acc')html=`<div class="field"><label>Name</label><input id="f_name" value="${obj.name||''}"></div><div class="grid2"><div class="field"><label>Start-Kontostand</label><input id="f_amount" type="number" step="0.01" value="${obj.startBalance??''}"></div><div class="field"><label>Symbol</label><input id="f_icon" value="${obj.icon||'💳'}"></div></div><div class="field"><label>Farbe</label><select id="f_color">${['blue','green','orange','purple','red','pink','teal'].map(c=>`<option ${obj.color===c?'selected':''}>${c}</option>`).join('')}</select></div>`;
if(type==='goal')html=`<div class="field"><label>Name</label><input id="f_name" value="${obj.name||''}"></div><div class="grid2"><div class="field"><label>Zielbetrag</label><input id="f_target" type="number" step="0.01" value="${obj.targetAmount||''}"></div><div class="field"><label>Gespart</label><input id="f_saved" type="number" step="0.01" value="${obj.savedAmount||''}"></div></div><div class="grid2"><div class="field"><label>Konto</label><select id="f_acc">${optionAccounts(obj.accountId||state.accounts[0]?.id)}</select></div><div class="field"><label>Zieldatum</label><input id="f_date" type="date" value="${obj.targetDate||''}"></div></div><div class="grid2"><div class="field"><label>Symbol</label><input id="f_icon" value="${obj.icon||'⭐'}"></div><div class="field"><label>Farbe</label><select id="f_color">${['blue','green','orange','purple','red','pink','teal'].map(c=>`<option ${obj.color===c?'selected':''}>${c}</option>`).join('')}</select></div></div><div class="field"><label>Notiz</label><textarea id="f_note">${obj.note||''}</textarea></div>`;
if(type==='budget')html=`<div class="grid2"><div class="field"><label>Kategorie</label><input id="f_cat" value="${obj.category||'Essen'}"></div><div class="field"><label>Limit</label><input id="f_amount" type="number" step="0.01" value="${obj.limit||''}"></div></div><div class="grid2"><div class="field"><label>Symbol</label><input id="f_icon" value="${obj.icon||'☷'}"></div><div class="field"><label>Farbe</label><select id="f_color">${['blue','green','orange','purple','red','pink','teal'].map(c=>`<option ${obj.color===c?'selected':''}>${c}</option>`).join('')}</select></div></div>`;
document.querySelectorAll('#modal').forEach(x=>x.remove());
let m=document.createElement('div');m.id='modal';m.className='modal show';m.innerHTML=`<div class="sheet"><div class="sheetHead"><button type="button" class="link" onclick="closeModal()">Abbrechen</button><h2>${title}</h2><span></span></div><div class="form">${html}</div><div class="actions">${is?`<button type="button" class="btn delete" onclick="delItem('${type}','${id}')">Löschen</button>`:''}<button type="button" class="btn secondary" onclick="closeModal()">Abbrechen</button><button type="button" class="btn" onclick="saveItem('${type}','${id}')">Speichern</button></div></div>`;document.body.appendChild(m)}
function closeModal(){document.querySelectorAll('#modal').forEach(x=>x.remove());render()}
function saveItem(type,id){let is=!!id, arr=type==='tx'?state.transactions:type==='rec'?state.recurring:type==='acc'?state.accounts:type==='goal'?state.goals:state.budgets;let o=is?arr.find(x=>x.id===id):{id:uid()};let val=x=>$('#'+x)?.value;
if(type==='tx'){let ty=val('f_type');Object.assign(o,{name:val('f_name'),amount:+val('f_amount'),category:ty==='transfer'?'Umbuchung':val('f_cat'),accountId:val('f_acc'),targetAccountId:val('f_tacc'),date:val('f_date'),note:val('f_note'),isIncome:ty==='income',isTransfer:ty==='transfer'})}
if(type==='rec')Object.assign(o,{name:val('f_name'),amount:+val('f_amount'),category:val('f_cat'),accountId:val('f_acc'),targetAccountId:val('f_tacc'),billingCycle:val('f_cycle'),nextDueDate:val('f_date'),icon:val('f_icon'),note:val('f_note'),isActive:val('f_active')==='true',type:val('f_type')});
if(type==='acc')Object.assign(o,{name:val('f_name'),startBalance:+val('f_amount'),icon:val('f_icon'),color:val('f_color')});
if(type==='goal')Object.assign(o,{name:val('f_name'),targetAmount:+val('f_target'),savedAmount:+val('f_saved'),accountId:val('f_acc'),icon:val('f_icon'),color:val('f_color'),targetDate:val('f_date'),note:val('f_note')});
if(type==='budget')Object.assign(o,{category:val('f_cat'),limit:+val('f_amount'),icon:val('f_icon'),color:val('f_color')});
if(!is)arr.push(o);save();closeModal()}
function delItem(type,id){if(!confirm('Wirklich löschen?'))return;let map={tx:'transactions',rec:'recurring',acc:'accounts',goal:'goals',budget:'budgets'};state[map[type]]=state[map[type]].filter(x=>x.id!==id);save();closeModal()}
function drawCharts(){let c=id=>document.getElementById(id); if(c('pie'))drawPie(c('pie'),categoryTotals().map(x=>x.total),categoryTotals().map(x=>x.category)); if(c('bars'))drawBars(c('bars'),last6()); if(c('line'))drawLine(c('line'),last6())}
function setupCanvas(canvas){let dpr=devicePixelRatio||1,w=canvas.clientWidth,h=260;canvas.width=w*dpr;canvas.height=h*dpr;let ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);return{ctx,w,h}}
function drawPie(canvas,vals,labels){let {ctx,w,h}=setupCanvas(canvas),sum=vals.reduce((a,b)=>a+b,0),ang=-Math.PI/2,colors=['#ff9f30','#ff5aa5','#3aa0ff','#af7cff','#ff4b55','#36d1c4','#34d567'];ctx.clearRect(0,0,w,h);if(!sum)return;vals.forEach((v,i)=>{let a=v/sum*Math.PI*2;ctx.beginPath();ctx.moveTo(w/2,h/2);ctx.arc(w/2,h/2,90,ang,ang+a);ctx.fillStyle=colors[i%colors.length];ctx.fill();ang+=a});ctx.beginPath();ctx.arc(w/2,h/2,52,0,7);ctx.fillStyle='#242427';ctx.fill()}
function drawBars(canvas,data){let {ctx,w,h}=setupCanvas(canvas),max=Math.max(...data.map(d=>Math.max(d.income,d.expenses)),1),bw=w/data.length/3;ctx.clearRect(0,0,w,h);data.forEach((d,i)=>{let x=i*w/data.length+w/data.length/2;ctx.fillStyle='#34d567';ctx.fillRect(x-bw-2,h-30-d.income/max*(h-55),bw,d.income/max*(h-55));ctx.fillStyle='#ff4b55';ctx.fillRect(x+2,h-30-d.expenses/max*(h-55),bw,d.expenses/max*(h-55));ctx.fillStyle='#aaa';ctx.fillText(d.month,x-18,h-8)})}
function drawLine(canvas,data){let {ctx,w,h}=setupCanvas(canvas),vals=data.map(d=>d.balance),min=Math.min(...vals,0),max=Math.max(...vals,1),pad=24;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#3aa0ff';ctx.lineWidth=3;ctx.beginPath();vals.forEach((v,i)=>{let x=pad+i*(w-pad*2)/(vals.length-1),y=h-30-(v-min)/(max-min||1)*(h-60);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#aaa';data.forEach((d,i)=>ctx.fillText(d.month,pad+i*(w-pad*2)/(data.length-1)-12,h-8))}
render();
