const KEY='finance_app_accountid_v1';
const uid=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random());
const eur=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n||0);
const today=()=>new Date().toISOString().slice(0,10);
const addMonths=(iso,m)=>{const d=new Date(iso);d.setMonth(d.getMonth()+m);return d.toISOString().slice(0,10)};
const data=load();let tab='overview';
function defaults(){const giro=uid(), cash=uid(), spar=uid();return{accounts:[{id:giro,name:'Giro',initialBalance:1150,icon:'💳',color:'blue'},{id:cash,name:'Bargeld',initialBalance:45,icon:'💶',color:'green'},{id:spar,name:'Spar',initialBalance:600,icon:'🏦',color:'purple'}],transactions:[{id:uid(),name:'Essen',amount:50,category:'Essen',accountId:giro,date:today(),note:'',isIncome:false}],recurring:[{id:uid(),name:'Netflix',amount:12.99,category:'Streaming',accountId:giro,targetAccountId:null,billingCycle:'monthly',nextDueDate:today(),icon:'📺',note:'',isActive:true,type:'expense'},{id:uid(),name:'Spotify',amount:10.99,category:'Musik',accountId:giro,targetAccountId:null,billingCycle:'monthly',nextDueDate:today(),icon:'🎵',note:'',isActive:true,type:'expense'},{id:uid(),name:'Sparen',amount:100,category:'Umbuchung',accountId:giro,targetAccountId:spar,billingCycle:'monthly',nextDueDate:today(),icon:'🔁',note:'',isActive:true,type:'transfer'}],goals:[{id:uid(),name:'Urlaub',targetAmount:1500,savedAmount:350,accountId:spar,icon:'✈️',color:'orange'}],budgets:[{id:uid(),category:'Essen',limit:200,icon:'🍴',color:'orange'}],categories:['Essen','Shopping','Auto','Freizeit','Gesundheit','Bildung','Haushalt','Kleidung','Sonstiges']}}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||defaults()}catch{return defaults()}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function accountName(id){return data.accounts.find(a=>a.id===id)?.name||'Konto gelöscht'}
function balance(a){return a.initialBalance+data.transactions.filter(t=>t.accountId===a.id).reduce((s,t)=>s+(t.isIncome?t.amount:-t.amount),0)}
function totalBalance(){return data.accounts.reduce((s,a)=>s+balance(a),0)}
function monthTx(){const ym=today().slice(0,7);return data.transactions.filter(t=>t.date.slice(0,7)===ym)}
function monthlyIncome(){return monthTx().filter(t=>t.isIncome).reduce((s,t)=>s+t.amount,0)}
function monthlyExpenses(){return monthTx().filter(t=>!t.isIncome&&t.category!=='Umbuchung').reduce((s,t)=>s+t.amount,0)}
function spent(cat){return monthTx().filter(t=>!t.isIncome&&t.category===cat).reduce((s,t)=>s+t.amount,0)}
function processDueRecurring(){let changed=false;const now=today();for(const r of data.recurring){let guard=0;while(r.isActive&&r.nextDueDate<=now&&guard<24){if(r.type==='income')data.transactions.push({id:uid(),name:r.name,amount:r.amount,category:r.category,accountId:r.accountId,date:r.nextDueDate,note:'Automatisch durch Vertrag',isIncome:true});if(r.type==='expense')data.transactions.push({id:uid(),name:r.name,amount:r.amount,category:r.category,accountId:r.accountId,date:r.nextDueDate,note:'Automatisch durch Vertrag',isIncome:false});if(r.type==='transfer'&&r.targetAccountId){data.transactions.push({id:uid(),name:r.name,amount:r.amount,category:'Umbuchung',accountId:r.accountId,date:r.nextDueDate,note:'Automatisch durch Vertrag',isIncome:false});data.transactions.push({id:uid(),name:r.name,amount:r.amount,category:'Umbuchung',accountId:r.targetAccountId,date:r.nextDueDate,note:'Automatisch durch Vertrag',isIncome:true})}r.nextDueDate=addMonths(r.nextDueDate,r.billingCycle==='yearly'?12:r.billingCycle==='quarterly'?3:1);changed=true;guard++}}if(changed)save()}
processDueRecurring();render();
function render(){document.getElementById('app').innerHTML=`<div class="top"><div class="title"><h1>${title()}</h1><button class="add" onclick="openAdd()">+</button></div></div><div class="wrap">${view()}</div><nav class="tabs">${['overview:Übersicht','recurring:Verträge','analysis:Analyse','goals:Sparen','budgets:Budgets'].map(x=>{let[a,b]=x.split(':');return`<button class="tab ${tab===a?'active':''}" onclick="tab='${a}';render()">${b}</button>`}).join('')}</nav><div class="fabbox" id="modal"></div>`;drawCharts()}
function title(){return{overview:'Übersicht',recurring:'Verträge',analysis:'Analyse',goals:'Sparen',budgets:'Budgets'}[tab]}
function view(){if(tab==='overview')return overview();if(tab==='recurring')return recurring();if(tab==='analysis')return analysis();if(tab==='goals')return goals();return budgets()}
function overview(){return`<section class="hero"><div class="label">Gesamtvermögen</div><div class="balance">${eur(totalBalance())}</div><div class="pillrow"><div class="pill green"><small>Einnahmen</small><b>${eur(monthlyIncome())}</b></div><div class="pill red"><small>Ausgaben</small><b>${eur(monthlyExpenses())}</b></div></div><div class="ok">✓ Noch ${eur(monthlyIncome()-monthlyExpenses())} verfügbar</div></section><section class="card"><div class="cardhead"><h2>Konten</h2><button class="link" onclick="openAccount()">Bearbeiten</button></div>${data.accounts.map(a=>row(a.icon,a.name,'Kontostand',eur(balance(a)))).join('')}</section><section class="card"><h2>Letzte Buchungen</h2>${data.transactions.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8).map(t=>row(t.isIncome?'⬇️':'⬆️',t.name,`${t.category} • ${accountName(t.accountId)} • ${t.date}`,`${t.isIncome?'+':'-'}${eur(t.amount)}`,t.isIncome?'pos':'neg')).join('')||'<div class="empty">Keine Buchungen</div>'}</section>`}
function row(icon,main,sub,amount,cls=''){return`<div class="row"><div class="icon">${icon}</div><div><div class="main">${main}</div><div class="sub">${sub}</div></div><div class="spacer"></div><div class="amount ${cls}">${amount}</div></div>`}
function recurring(){return`<section class="card"><button class="primary" onclick="processDueRecurring();render()">Fällige Verträge jetzt prüfen</button></section><section class="card">${data.recurring.map(r=>row(r.icon||'📄',r.name,`${r.type==='transfer'?accountName(r.accountId)+' → '+accountName(r.targetAccountId):accountName(r.accountId)} • ${r.nextDueDate}`,`${r.type==='income'?'+':'-'}${eur(r.amount)}`,r.type==='income'?'pos':'')).join('')}</section>`}
function analysis(){const cats=data.categories.map(c=>({c,v:spent(c)})).filter(x=>x.v>0);return`<section class="card"><h2>Ausgaben nach Kategorie</h2><canvas id="catChart"></canvas>${cats.map(x=>row('•',x.c,'',eur(x.v))).join('')||'<div class="empty">Keine Daten</div>'}</section><section class="card"><h2>Kontostände</h2>${data.accounts.map(a=>row(a.icon,a.name,'',eur(balance(a)))).join('')}</section>`}
function goals(){return`<section class="card">${data.goals.map(g=>{let p=g.targetAmount?Math.min(g.savedAmount/g.targetAmount,1):0;return`<div class="row"><div class="icon">${g.icon}</div><div style="flex:1"><div class="main">${g.name}</div><div class="sub">Konto: ${accountName(g.accountId)} • ${eur(g.savedAmount)} von ${eur(g.targetAmount)}</div><div class="progress"><div class="bar" style="width:${p*100}%"></div></div></div><b>${Math.round(p*100)}%</b></div>`}).join('')}</section>`}
function budgets(){return`<section class="card">${data.budgets.map(b=>{let s=spent(b.category),p=b.limit?Math.min(s/b.limit,1):0;return`<div class="row"><div class="icon">${b.icon}</div><div style="flex:1"><div class="main">${b.category}</div><div class="sub">${eur(s)} / ${eur(b.limit)}</div><div class="progress"><div class="bar" style="width:${p*100}%;background:${s>b.limit?'var(--red)':'var(--green)'}"></div></div></div></div>`}).join('')}</section>`}
function optionsAccounts(sel=''){return data.accounts.map(a=>`<option value="${a.id}" ${a.id===sel?'selected':''}>${a.name}</option>`).join('')}
function openAdd(){const m=document.getElementById('modal');m.style.display='flex';const first=data.accounts[0]?.id||'';m.innerHTML=`<div class="sheet"><h2>Neue Buchung</h2><div class="formgrid"><label>Name<input id="n"></label><label>Betrag<input id="a" type="number" step="0.01"></label><label>Art<select id="type"><option value="expense">Ausgabe</option><option value="income">Einnahme</option></select></label><label>Kategorie<input id="c" value="Essen"></label><label>Konto<select id="acc">${optionsAccounts(first)}</select></label><label>Datum<input id="d" type="date" value="${today()}"></label></div><div class="actions"><button onclick="closeM()">Abbrechen</button><button class="primary" onclick="saveTx()">Speichern</button></div></div>`}
function saveTx(){const type=document.getElementById('type').value;data.transactions.push({id:uid(),name:n.value,amount:+a.value,category:c.value,accountId:acc.value,date:d.value,note:'',isIncome:type==='income'});save();closeM();render()}
function openAccount(){const m=document.getElementById('modal');m.style.display='flex';m.innerHTML=`<div class="sheet"><h2>Konto hinzufügen</h2><div class="formgrid"><label>Name<input id="an"></label><label>Startkontostand<input id="ab" type="number" step="0.01"></label></div><div class="actions"><button onclick="closeM()">Abbrechen</button><button class="primary" onclick="data.accounts.push({id:uid(),name:an.value,initialBalance:+ab.value,icon:'💳',color:'blue'});save();closeM();render()">Speichern</button></div></div>`}
function closeM(){document.getElementById('modal').style.display='none'}
function drawCharts(){const cvs=document.getElementById('catChart');if(!cvs)return;const ctx=cvs.getContext('2d'),w=cvs.width=cvs.clientWidth*2,h=cvs.height=cvs.clientHeight*2;ctx.clearRect(0,0,w,h);const cats=data.categories.map(c=>({c,v:spent(c)})).filter(x=>x.v>0),sum=cats.reduce((s,x)=>s+x.v,0);let a=-Math.PI/2;const colors=['#ff9f0a','#ff375f','#0a84ff','#bf5af2','#30d158','#64d2ff','#ffd60a'];cats.forEach((x,i)=>{const b=a+(x.v/sum)*Math.PI*2;ctx.beginPath();ctx.moveTo(w/2,h/2);ctx.arc(w/2,h/2,Math.min(w,h)/2.5,a,b);ctx.closePath();ctx.fillStyle=colors[i%colors.length];ctx.fill();a=b})}
